# Generated by Django 4.2.1 on 2023-05-25 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='If the instance is enabled', verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time was updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name for document.', max_length=255, unique=True, verbose_name='Name')),
                ('legal_person', models.BooleanField(default=False, help_text='Legal person for document.', verbose_name='Legal Person')),
                ('natural_person', models.BooleanField(default=False, help_text='Natural person for document.', verbose_name='Natural Person')),
                ('created_for', models.ForeignKey(help_text='User who created.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created For')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
