api:
  insecure: true

log:
  filePath: "/var/log/traefik/traefik.log"
  level: "DEBUG"

accessLog:
  filePath: "/var/log/traefik/access.log"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
